### ISSUE TITLE
Installing an Add-on Instance

### ISSUE THREAD

**Issue by Unichron** [opentelekomcloud-docs/cloud-container-engine#40]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/api-ref/source/apis/add-on_management/installing_an_add-on_instance.rst

The addon .spec.values object is missing the "flavor" parameter (next to basic and custom). This is for configuring replica count and resource requests/limits of the addons. I think the impacted pages are installing and updating (if it's possible to update, haven't checked).

**Comment by oeotvos** [comment]
Hi, /api/v3/addontemplates returns the information of how request body during specific addon creation should look like. The flavor and also other parameters are not described because every addon can have different parameters. 
The API reference contains examples (e.g. Updating an Add-on) with usage of the flavor.

**Anyway, thank you for your remark, we will definitely update the add-on spec field description with the most common parameters like flavor, etc. and make a usage of this API more obvious.**

example of coredns creation:
{
"kind": "Addon",
"apiVersion": "v3",
"metadata": {
	"annotations": {
		"addon.install/type": "install"
		}
	},
"spec": {
	"clusterID": "cf59fc4a-cfb8-11ed-89cc-02550a10004e",
	"version": "1.25.1",
	"addonTemplateName": "coredns",
	"values": {
		"basic": {},
		"custom": {
			"stub_domains": "",
			"upstream_nameservers": ""
		},
		"flavor": {
            "description": "Has only one instance",
            "name": "Single",
            "replicas": 1,
            "resources": [
                {
                    "limitsCpu": "100m",
                    "limitsMem": "128Mi",
                    "name": "coredns",
                    "requestsCpu": "100m",
                    "requestsMem": "128Mi"
                }
            ]
        }
    }
}
}

(Internal demand opened #CONT-1578)

**Comment by oeotvos** [comment]
Internal demand OTCPR-5601.

**Comment by oeotvos** [comment]
The demand has been resolved by adding required information to API and UMN
https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/add-on_instance_parameters/index.html 
https://docs.otc.t-systems.com/cloud-container-engine/umn/add-ons/overview.html
